### ISSUE TITLE
端口可配置

### ISSUE THREAD

**Issue by dengmingli** [zt5/egret-helper#1]
端口只能固定3000，不能配置？

**Comment by zt5** [comment]
### 更新了v2.0.41版本
添加了Server Cmd配置 (vscode -> 文件 -> 首选项 -> 设置 -> 扩展 -> Egret Helper -> Server Cmd)
里面替换成 **egret run --serverOnly  --port 6666** 即可 6666就是你要设置的端口号

**Comment by zt5** [comment]
2.0.42版本 添加了port设置
