### ISSUE TITLE
在ts文件断点，运行到断点会跳到相应的js 文件，可以做到运行到断点后，断点在ts文件吗？

### ISSUE THREAD

**Issue by ycllz** [zt5/egret-helper#2]
在ts文件断点，运行到断点会跳到相应的js 文件，可以做到运行到断点后，断点在ts文件吗？

目前最好用的，谢谢。

**Comment by zt5** [comment]
有项目例子吗？ 目前这个插件我一直在用，没有碰到这种情况

**Comment by zt5** [comment]
没有反馈 似乎解决了？ 有问题再重新打开

**Comment by ycllz** [comment]
重启系统可以解决，我也是今天发现。平时太忙了，又搞回wing去用，现在发现居然可以了。谢谢。
