### ISSUE TITLE
升级3.X版本之后，编译完成后根目录在bin-debug

### ISSUE THREAD

**Issue by irwinmc** [zt5/egret-helper#3]
3.0版本使用webpack编译之后manifest变成老版本，即带有所有debug目录下的js，2.x版本是只有一个main.js。运行调试服务器，根目录范围在bin-debug下，导致其他index.html引用的css\js失效，找不到路径。调试过程中，部分文件断点位置不匹配。

**Comment by zt5** [comment]
新版本目前确实有问题 正在修改
如果用老版本编译 可以通过边栏的 扩展 -> Egret-helper -> 齿轮按钮 -> 安装另一个版本 -> 2.0.42 回滚到上一个版本的插件

**Comment by zt5** [comment]
@irwinmc 新版本已发布 再试下

**Comment by irwinmc** [comment]
@zt5 你太棒了，应该已经解决。非常感谢！
